=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module OpenapiClient
  class CreateTrustApplicationAttributes
    attr_accessor :name

    attr_accessor :state_of_incorporation

    attr_accessor :revocability

    attr_accessor :source_of_funds

    attr_accessor :tax_id

    attr_accessor :grantor

    attr_accessor :trustees

    attr_accessor :beneficiaries

    attr_accessor :contact

    attr_accessor :ip

    attr_accessor :tags

    attr_accessor :idempotency_key

    attr_accessor :device_fingerprints

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'state_of_incorporation' => :'stateOfIncorporation',
        :'revocability' => :'revocability',
        :'source_of_funds' => :'sourceOfFunds',
        :'tax_id' => :'taxId',
        :'grantor' => :'grantor',
        :'trustees' => :'trustees',
        :'beneficiaries' => :'beneficiaries',
        :'contact' => :'contact',
        :'ip' => :'ip',
        :'tags' => :'tags',
        :'idempotency_key' => :'idempotencyKey',
        :'device_fingerprints' => :'deviceFingerprints'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'state_of_incorporation' => :'String',
        :'revocability' => :'String',
        :'source_of_funds' => :'String',
        :'tax_id' => :'String',
        :'grantor' => :'Grantor',
        :'trustees' => :'Array<Trustee>',
        :'beneficiaries' => :'Array<Beneficiary>',
        :'contact' => :'TrustContact',
        :'ip' => :'String',
        :'tags' => :'Object',
        :'idempotency_key' => :'String',
        :'device_fingerprints' => :'Array<DeviceFingerprint>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::CreateTrustApplicationAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::CreateTrustApplicationAttributes`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'state_of_incorporation')
        self.state_of_incorporation = attributes[:'state_of_incorporation']
      else
        self.state_of_incorporation = nil
      end

      if attributes.key?(:'revocability')
        self.revocability = attributes[:'revocability']
      else
        self.revocability = nil
      end

      if attributes.key?(:'source_of_funds')
        self.source_of_funds = attributes[:'source_of_funds']
      else
        self.source_of_funds = nil
      end

      if attributes.key?(:'tax_id')
        self.tax_id = attributes[:'tax_id']
      else
        self.tax_id = nil
      end

      if attributes.key?(:'grantor')
        self.grantor = attributes[:'grantor']
      else
        self.grantor = nil
      end

      if attributes.key?(:'trustees')
        if (value = attributes[:'trustees']).is_a?(Array)
          self.trustees = value
        end
      else
        self.trustees = nil
      end

      if attributes.key?(:'beneficiaries')
        if (value = attributes[:'beneficiaries']).is_a?(Array)
          self.beneficiaries = value
        end
      else
        self.beneficiaries = nil
      end

      if attributes.key?(:'contact')
        self.contact = attributes[:'contact']
      else
        self.contact = nil
      end

      if attributes.key?(:'ip')
        self.ip = attributes[:'ip']
      end

      if attributes.key?(:'tags')
        self.tags = attributes[:'tags']
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      end

      if attributes.key?(:'device_fingerprints')
        if (value = attributes[:'device_fingerprints']).is_a?(Array)
          self.device_fingerprints = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 255
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 255.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be great than or equal to 1.')
      end

      if @state_of_incorporation.nil?
        invalid_properties.push('invalid value for "state_of_incorporation", state_of_incorporation cannot be nil.')
      end

      if @state_of_incorporation.to_s.length > 2
        invalid_properties.push('invalid value for "state_of_incorporation", the character length must be smaller than or equal to 2.')
      end

      if @state_of_incorporation.to_s.length < 2
        invalid_properties.push('invalid value for "state_of_incorporation", the character length must be great than or equal to 2.')
      end

      if @revocability.nil?
        invalid_properties.push('invalid value for "revocability", revocability cannot be nil.')
      end

      if @source_of_funds.nil?
        invalid_properties.push('invalid value for "source_of_funds", source_of_funds cannot be nil.')
      end

      if @tax_id.nil?
        invalid_properties.push('invalid value for "tax_id", tax_id cannot be nil.')
      end

      if @grantor.nil?
        invalid_properties.push('invalid value for "grantor", grantor cannot be nil.')
      end

      if @trustees.nil?
        invalid_properties.push('invalid value for "trustees", trustees cannot be nil.')
      end

      if @beneficiaries.nil?
        invalid_properties.push('invalid value for "beneficiaries", beneficiaries cannot be nil.')
      end

      if @contact.nil?
        invalid_properties.push('invalid value for "contact", contact cannot be nil.')
      end

      if !@idempotency_key.nil? && @idempotency_key.to_s.length > 255
        invalid_properties.push('invalid value for "idempotency_key", the character length must be smaller than or equal to 255.')
      end

      if !@idempotency_key.nil? && @idempotency_key.to_s.length < 1
        invalid_properties.push('invalid value for "idempotency_key", the character length must be great than or equal to 1.')
      end

      if !@device_fingerprints.nil? && @device_fingerprints.length > 1
        invalid_properties.push('invalid value for "device_fingerprints", number of items must be less than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length > 255
      return false if @name.to_s.length < 1
      return false if @state_of_incorporation.nil?
      return false if @state_of_incorporation.to_s.length > 2
      return false if @state_of_incorporation.to_s.length < 2
      return false if @revocability.nil?
      revocability_validator = EnumAttributeValidator.new('String', ["Revocable", "Irrevocable"])
      return false unless revocability_validator.valid?(@revocability)
      return false if @source_of_funds.nil?
      source_of_funds_validator = EnumAttributeValidator.new('String', ["Inheritance", "Salary", "Savings", "InvestmentReturns", "Gifts"])
      return false unless source_of_funds_validator.valid?(@source_of_funds)
      return false if @tax_id.nil?
      return false if @grantor.nil?
      return false if @trustees.nil?
      return false if @beneficiaries.nil?
      return false if @contact.nil?
      return false if !@idempotency_key.nil? && @idempotency_key.to_s.length > 255
      return false if !@idempotency_key.nil? && @idempotency_key.to_s.length < 1
      return false if !@device_fingerprints.nil? && @device_fingerprints.length > 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 255
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 255.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be great than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] state_of_incorporation Value to be assigned
    def state_of_incorporation=(state_of_incorporation)
      if state_of_incorporation.nil?
        fail ArgumentError, 'state_of_incorporation cannot be nil'
      end

      if state_of_incorporation.to_s.length > 2
        fail ArgumentError, 'invalid value for "state_of_incorporation", the character length must be smaller than or equal to 2.'
      end

      if state_of_incorporation.to_s.length < 2
        fail ArgumentError, 'invalid value for "state_of_incorporation", the character length must be great than or equal to 2.'
      end

      @state_of_incorporation = state_of_incorporation
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] revocability Object to be assigned
    def revocability=(revocability)
      validator = EnumAttributeValidator.new('String', ["Revocable", "Irrevocable"])
      unless validator.valid?(revocability)
        fail ArgumentError, "invalid value for \"revocability\", must be one of #{validator.allowable_values}."
      end
      @revocability = revocability
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] source_of_funds Object to be assigned
    def source_of_funds=(source_of_funds)
      validator = EnumAttributeValidator.new('String', ["Inheritance", "Salary", "Savings", "InvestmentReturns", "Gifts"])
      unless validator.valid?(source_of_funds)
        fail ArgumentError, "invalid value for \"source_of_funds\", must be one of #{validator.allowable_values}."
      end
      @source_of_funds = source_of_funds
    end

    # Custom attribute writer method with validation
    # @param [Object] tags Value to be assigned
    def tags=(tags)
      if tags.nil?
        fail ArgumentError, 'tags cannot be nil'
      end

      @tags = tags
    end

    # Custom attribute writer method with validation
    # @param [Object] idempotency_key Value to be assigned
    def idempotency_key=(idempotency_key)
      if idempotency_key.nil?
        fail ArgumentError, 'idempotency_key cannot be nil'
      end

      if idempotency_key.to_s.length > 255
        fail ArgumentError, 'invalid value for "idempotency_key", the character length must be smaller than or equal to 255.'
      end

      if idempotency_key.to_s.length < 1
        fail ArgumentError, 'invalid value for "idempotency_key", the character length must be great than or equal to 1.'
      end

      @idempotency_key = idempotency_key
    end

    # Custom attribute writer method with validation
    # @param [Object] device_fingerprints Value to be assigned
    def device_fingerprints=(device_fingerprints)
      if device_fingerprints.nil?
        fail ArgumentError, 'device_fingerprints cannot be nil'
      end

      if device_fingerprints.length > 1
        fail ArgumentError, 'invalid value for "device_fingerprints", number of items must be less than or equal to 1.'
      end

      @device_fingerprints = device_fingerprints
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          state_of_incorporation == o.state_of_incorporation &&
          revocability == o.revocability &&
          source_of_funds == o.source_of_funds &&
          tax_id == o.tax_id &&
          grantor == o.grantor &&
          trustees == o.trustees &&
          beneficiaries == o.beneficiaries &&
          contact == o.contact &&
          ip == o.ip &&
          tags == o.tags &&
          idempotency_key == o.idempotency_key &&
          device_fingerprints == o.device_fingerprints
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, state_of_incorporation, revocability, source_of_funds, tax_id, grantor, trustees, beneficiaries, contact, ip, tags, idempotency_key, device_fingerprints].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
