=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::BusinessAnnualRevenue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::BusinessAnnualRevenue do
  let(:instance) { OpenapiClient::BusinessAnnualRevenue.new }

  describe 'test an instance of BusinessAnnualRevenue' do
    it 'should create an instance of BusinessAnnualRevenue' do
      expect(instance).to be_instance_of(OpenapiClient::BusinessAnnualRevenue)
    end
  end
end
