=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CounterpartyRelationship
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CounterpartyRelationship do
  let(:instance) { OpenapiClient::CounterpartyRelationship.new }

  describe 'test an instance of CounterpartyRelationship' do
    it 'should create an instance of CounterpartyRelationship' do
      expect(instance).to be_instance_of(OpenapiClient::CounterpartyRelationship)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
