=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PatchIndividualVirtualDebitCardAttributes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PatchIndividualVirtualDebitCardAttributes do
  let(:instance) { OpenapiClient::PatchIndividualVirtualDebitCardAttributes.new }

  describe 'test an instance of PatchIndividualVirtualDebitCardAttributes' do
    it 'should create an instance of PatchIndividualVirtualDebitCardAttributes' do
      expect(instance).to be_instance_of(OpenapiClient::PatchIndividualVirtualDebitCardAttributes)
    end
  end
  describe 'test attribute "tags"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "limits"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "default_funding_account_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
