=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SourceOfFunds
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SourceOfFunds do
  let(:instance) { OpenapiClient::SourceOfFunds.new }

  describe 'test an instance of SourceOfFunds' do
    it 'should create an instance of SourceOfFunds' do
      expect(instance).to be_instance_of(OpenapiClient::SourceOfFunds)
    end
  end
end
