=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'date'
require 'time'

module OpenapiClient
  class SourceOfFunds
    INHERITANCE = "Inheritance".freeze
    SALARY = "Salary".freeze
    SAVINGS = "Savings".freeze
    INVESTMENT_RETURNS = "InvestmentReturns".freeze
    GIFTS = "Gifts".freeze

    def self.all_vars
      @all_vars ||= [INHERITANCE, SALARY, SAVINGS, INVESTMENT_RETURNS, GIFTS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SourceOfFunds.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SourceOfFunds"
    end
  end
end
