=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.3.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

module UnitOpenapiRubySdk
  VERSION = '1.0.0'
end
