=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AdvanceReceivedPaymentApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AdvanceReceivedPaymentApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AdvanceReceivedPaymentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdvanceReceivedPaymentApi' do
    it 'should create an instance of AdvanceReceivedPaymentApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AdvanceReceivedPaymentApi)
    end
  end

  # unit tests for execute
  # Advance Received Payment by Id
  # Advance a Received Payment via API 
  # @param payment_id ID of the payment to advance
  # @param [Hash] opts the optional parameters
  # @return [UnitPaymentResponse2]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
