=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CreateRewardApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CreateRewardApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CreateRewardApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateRewardApi' do
    it 'should create an instance of CreateRewardApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CreateRewardApi)
    end
  end

  # unit tests for execute
  # Create Reward
  # Create a Reward via API 
  # @param execute_request13 Create Reward Request
  # @param [Hash] opts the optional parameters
  # @return [UnitRewardResponse]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
