=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CreateCheckDepositApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CreateCheckDepositApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CreateCheckDepositApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateCheckDepositApi' do
    it 'should create an instance of CreateCheckDepositApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CreateCheckDepositApi)
    end
  end

  # unit tests for execute
  # Create Check Deposit
  # Create a Check Deposit via API 
  # @param execute_request15 Create Check Deposit Request
  # @param [Hash] opts the optional parameters
  # @return [UnitCheckDepositResponse]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
