=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DeleteCounterpartyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DeleteCounterpartyApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DeleteCounterpartyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeleteCounterpartyApi' do
    it 'should create an instance of DeleteCounterpartyApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DeleteCounterpartyApi)
    end
  end

  # unit tests for execute
  # Delete Counterparty by Id
  # Delete Counterparty via API 
  # @param counterparty_id ID of the counterparty to delete
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
