=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::GetAuthorizationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GetAuthorizationApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::GetAuthorizationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetAuthorizationApi' do
    it 'should create an instance of GetAuthorizationApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::GetAuthorizationApi)
    end
  end

  # unit tests for execute
  # Get Authorization by Id
  # Get a Authorization from API 
  # @param authorization_id ID of the authorization to get
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_none_authorized 
  # @return [UnitAuthorizationResponse]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
