=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::GetListPaymentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GetListPaymentsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::GetListPaymentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetListPaymentsApi' do
    it 'should create an instance of GetListPaymentsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::GetListPaymentsApi)
    end
  end

  # unit tests for execute
  # Get List Payments
  # Get List Payments from API 
  # @param [Hash] opts the optional parameters
  # @option opts [ListPageParametersObject] :page 
  # @option opts [ExecuteFilterParameter3] :filter 
  # @option opts [String] :include 
  # @option opts [String] :sort 
  # @return [UnitPaymentListResponse]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
