=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::GetListRewardsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GetListRewardsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::GetListRewardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetListRewardsApi' do
    it 'should create an instance of GetListRewardsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::GetListRewardsApi)
    end
  end

  # unit tests for execute
  # Get Rewards List
  # Get Rewards List from API 
  # @param [Hash] opts the optional parameters
  # @option opts [ListPageParametersObject] :page 
  # @option opts [ExecuteFilterParameter8] :filter 
  # @option opts [String] :sort 
  # @option opts [String] :include 
  # @return [UnitRewardsListResponse]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
