=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::RetrieveBarcodeImageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RetrieveBarcodeImageApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::RetrieveBarcodeImageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RetrieveBarcodeImageApi' do
    it 'should create an instance of RetrieveBarcodeImageApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::RetrieveBarcodeImageApi)
    end
  end

  # unit tests for execute
  # Get Barcode Image
  # Retrieves a cash deposit barcode image using the unique barcode number provided by the Generate Barcode endpoint.
  # @param barcode_number The unique identifier of a barcode, obtained from Generate Barcode endpoint.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
