=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UnfreezeACardApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UnfreezeACardApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UnfreezeACardApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UnfreezeACardApi' do
    it 'should create an instance of UnfreezeACardApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UnfreezeACardApi)
    end
  end

  # unit tests for execute
  # Unfreeze a Card
  # Unfreeze a Card via API 
  # @param card_id ID of the card to unfreeze
  # @param [Hash] opts the optional parameters
  # @return [UnitCardResponse]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
