=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UpdateWebhookApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UpdateWebhookApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UpdateWebhookApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdateWebhookApi' do
    it 'should create an instance of UpdateWebhookApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UpdateWebhookApi)
    end
  end

  # unit tests for execute
  # Update Webhook
  # Update a Webhook via API 
  # @param webhook_id ID of the Webhook to update
  # @param update_unit_request Update Webhook Request
  # @param [Hash] opts the optional parameters
  # @return [UnitWebhookResponse]
  describe 'execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
