=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module UnitOpenapiRubySdk
  class DepositLimitsAllOfAttributesAchLimits
    attr_accessor :daily_debit

    attr_accessor :daily_credit

    attr_accessor :monthly_debit

    attr_accessor :monthly_debit_soft

    attr_accessor :daily_debit_soft

    attr_accessor :monthly_credit

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'daily_debit' => :'dailyDebit',
        :'daily_credit' => :'dailyCredit',
        :'monthly_debit' => :'monthlyDebit',
        :'monthly_debit_soft' => :'monthlyDebitSoft',
        :'daily_debit_soft' => :'dailyDebitSoft',
        :'monthly_credit' => :'monthlyCredit'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'daily_debit' => :'Float',
        :'daily_credit' => :'Float',
        :'monthly_debit' => :'Float',
        :'monthly_debit_soft' => :'Float',
        :'daily_debit_soft' => :'Float',
        :'monthly_credit' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `UnitOpenapiRubySdk::DepositLimitsAllOfAttributesAchLimits` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `UnitOpenapiRubySdk::DepositLimitsAllOfAttributesAchLimits`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'daily_debit')
        self.daily_debit = attributes[:'daily_debit']
      else
        self.daily_debit = nil
      end

      if attributes.key?(:'daily_credit')
        self.daily_credit = attributes[:'daily_credit']
      else
        self.daily_credit = nil
      end

      if attributes.key?(:'monthly_debit')
        self.monthly_debit = attributes[:'monthly_debit']
      else
        self.monthly_debit = nil
      end

      if attributes.key?(:'monthly_debit_soft')
        self.monthly_debit_soft = attributes[:'monthly_debit_soft']
      end

      if attributes.key?(:'daily_debit_soft')
        self.daily_debit_soft = attributes[:'daily_debit_soft']
      end

      if attributes.key?(:'monthly_credit')
        self.monthly_credit = attributes[:'monthly_credit']
      else
        self.monthly_credit = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @daily_debit.nil?
        invalid_properties.push('invalid value for "daily_debit", daily_debit cannot be nil.')
      end

      if @daily_credit.nil?
        invalid_properties.push('invalid value for "daily_credit", daily_credit cannot be nil.')
      end

      if @monthly_debit.nil?
        invalid_properties.push('invalid value for "monthly_debit", monthly_debit cannot be nil.')
      end

      if @monthly_credit.nil?
        invalid_properties.push('invalid value for "monthly_credit", monthly_credit cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @daily_debit.nil?
      return false if @daily_credit.nil?
      return false if @monthly_debit.nil?
      return false if @monthly_credit.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          daily_debit == o.daily_debit &&
          daily_credit == o.daily_credit &&
          monthly_debit == o.monthly_debit &&
          monthly_debit_soft == o.monthly_debit_soft &&
          daily_debit_soft == o.daily_debit_soft &&
          monthly_credit == o.monthly_credit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [daily_debit, daily_credit, monthly_debit, monthly_debit_soft, daily_debit_soft, monthly_credit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = UnitOpenapiRubySdk.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
