=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.2.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module UnitOpenapiRubySdk
  class SoleProprietorshipAnnualRevenue
    UP_TO50K = "UpTo50k".freeze
    BETWEEN50K_AND100K = "Between50kAnd100k".freeze
    BETWEEN100K_AND200K = "Between100kAnd200k".freeze
    BETWEEN200K_AND500K = "Between200kAnd500k".freeze
    OVER500K = "Over500k".freeze

    def self.all_vars
      @all_vars ||= [UP_TO50K, BETWEEN50K_AND100K, BETWEEN100K_AND200K, BETWEEN200K_AND500K, OVER500K].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SoleProprietorshipAnnualRevenue.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SoleProprietorshipAnnualRevenue"
    end
  end
end
