=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.3.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module UnitOpenapiRubySdk
  class ThreadBusinessUsNexus
    EMPLOYEES = "Employees".freeze
    CUSTOMERS = "Customers".freeze
    PHYSICAL_OFFICE_OR_FACILITY = "PhysicalOfficeOrFacility".freeze
    BANKING_RELATIONSHIPS = "BankingRelationships".freeze
    NOT_AVAILABLE = "NotAvailable".freeze

    def self.all_vars
      @all_vars ||= [EMPLOYEES, CUSTOMERS, PHYSICAL_OFFICE_OR_FACILITY, BANKING_RELATIONSHIPS, NOT_AVAILABLE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ThreadBusinessUsNexus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ThreadBusinessUsNexus"
    end
  end
end
