=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.3.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module UnitOpenapiRubySdk
  class ThreadIndividualAccountPurpose
    PAYROLL_OR_DIRECT_DEPOSIT = "PayrollOrDirectDeposit".freeze
    PERSONAL_SAVINGS_OR_EMERGENCY_FUND = "PersonalSavingsOrEmergencyFund".freeze
    EVERYDAY_SPENDING = "EverydaySpending".freeze
    DOMESTIC_P2_P_AND_BILL_PAY = "DomesticP2PAndBillPay".freeze
    INTERNATIONAL_REMITTANCES = "InternationalRemittances".freeze
    CASH_HEAVY_PERSONAL_INCOME = "CashHeavyPersonalIncome".freeze
    PROPERTY_PURCHASE_OR_INVESTMENT = "PropertyPurchaseOrInvestment".freeze
    EDUCATION_OR_STUDENT_USE = "EducationOrStudentUse".freeze
    TRUST_OR_ESTATE_DISTRIBUTIONS = "TrustOrEstateDistributions".freeze
    CRYPTOCURRENCY = "Cryptocurrency".freeze

    def self.all_vars
      @all_vars ||= [PAYROLL_OR_DIRECT_DEPOSIT, PERSONAL_SAVINGS_OR_EMERGENCY_FUND, EVERYDAY_SPENDING, DOMESTIC_P2_P_AND_BILL_PAY, INTERNATIONAL_REMITTANCES, CASH_HEAVY_PERSONAL_INCOME, PROPERTY_PURCHASE_OR_INVESTMENT, EDUCATION_OR_STUDENT_USE, TRUST_OR_ESTATE_DISTRIBUTIONS, CRYPTOCURRENCY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ThreadIndividualAccountPurpose.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ThreadIndividualAccountPurpose"
    end
  end
end
