=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.3.2

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module UnitOpenapiRubySdk
  class ThreadBusinessIndustry
    GROCERY_STORES_OR_SUPERMARKETS = "GroceryStoresOrSupermarkets".freeze
    CONVENIENCE_STORES = "ConvenienceStores".freeze
    SPECIALTY_FOOD_RETAILERS = "SpecialtyFoodRetailers".freeze
    GAS_STATIONS_WITH_RETAIL = "GasStationsWithRetail".freeze
    GENERAL_MERCHANDISE_OR_DEPARTMENT_STORES = "GeneralMerchandiseOrDepartmentStores".freeze
    ONLINE_RETAIL_OR_E_COMMERCE = "OnlineRetailOrECommerce".freeze
    SUBSCRIPTION_AND_MEMBERSHIP_PLATFORMS = "SubscriptionAndMembershipPlatforms".freeze
    DIRECT_TO_CONSUMER_BRANDS = "DirectToConsumerBrands".freeze
    CANNABIS = "Cannabis".freeze
    BANKS_OR_CREDIT_UNIONS = "BanksOrCreditUnions".freeze
    FIN_TECH_OR_PAYMENT_PROCESSING = "FinTechOrPaymentProcessing".freeze
    INSURANCE_PROVIDERS = "InsuranceProviders".freeze
    INVESTMENT_ADVISORS_OR_BROKER_DEALERS = "InvestmentAdvisorsOrBrokerDealers".freeze
    LENDING_OR_MORTGAGE_COMPANIES = "LendingOrMortgageCompanies".freeze
    TREASURY_MANAGEMENT_PLATFORMS = "TreasuryManagementPlatforms".freeze
    PERSONAL_FINANCE_APPS_OR_AI_ASSISTANTS = "PersonalFinanceAppsOrAIAssistants".freeze
    RETIREMENT_PLANNING = "RetirementPlanning".freeze
    REAL_ESTATE_INVESTMENT_PLATFORMS = "RealEstateInvestmentPlatforms".freeze
    MONEY_SERVICE_BUSINESSES = "MoneyServiceBusinesses".freeze
    CRYPTOCURRENCY = "Cryptocurrency".freeze
    DEBT_COLLECTION = "DebtCollection".freeze
    PAYDAY_LENDING = "PaydayLending".freeze
    GAMBLING = "Gambling".freeze
    FARMS_OR_AGRICULTURAL_PRODUCERS = "FarmsOrAgriculturalProducers".freeze
    FOOD_WHOLESALERS_OR_DISTRIBUTORS = "FoodWholesalersOrDistributors".freeze
    RESTAURANTS_OR_CAFES = "RestaurantsOrCafes".freeze
    BARS_OR_NIGHTCLUBS = "BarsOrNightclubs".freeze
    CATERING_SERVICES = "CateringServices".freeze
    FARMERS_MARKETS = "FarmersMarkets".freeze
    RESTAURANT_TECH_AND_POS_PROVIDERS = "RestaurantTechAndPOSProviders".freeze
    HOSPITALS_OR_CLINICS = "HospitalsOrClinics".freeze
    PHARMACIES = "Pharmacies".freeze
    MEDICAL_EQUIPMENT_SUPPLIERS = "MedicalEquipmentSuppliers".freeze
    BIOTECHNOLOGY_FIRMS = "BiotechnologyFirms".freeze
    HOME_HEALTH_SERVICES = "HomeHealthServices".freeze
    HEALTHCARE_STAFFING_PLATFORMS = "HealthcareStaffingPlatforms".freeze
    WELLNESS_AND_BENEFITS_PLATFORMS = "WellnessAndBenefitsPlatforms".freeze
    HEALTHCARE_AND_SOCIAL_ASSISTANCE = "HealthcareAndSocialAssistance".freeze
    LEGAL_SERVICES = "LegalServices".freeze
    ACCOUNTING_OR_AUDITING_FIRMS = "AccountingOrAuditingFirms".freeze
    CONSULTING_FIRMS = "ConsultingFirms".freeze
    MARKETING_OR_ADVERTISING_AGENCIES = "MarketingOrAdvertisingAgencies".freeze
    REAL_ESTATE_AGENTS_OR_PROPERTY_MANAGERS = "RealEstateAgentsOrPropertyManagers".freeze
    CORPORATE_SERVICES_AND_INCORPORATION = "CorporateServicesAndIncorporation".freeze
    HR_AND_WORKFORCE_MANAGEMENT_PLATFORMS = "HRAndWorkforceManagementPlatforms".freeze
    DIRECT_MARKETING_OR_TELEMARKETING = "DirectMarketingOrTelemarketing".freeze
    LEGAL_ACCOUNTING_CONSULTING_OR_COMPUTER_PROGRAMMING = "LegalAccountingConsultingOrComputerProgramming".freeze
    CHEMICAL_MANUFACTURING = "ChemicalManufacturing".freeze
    ELECTRONICS_OR_HARDWARE_MANUFACTURING = "ElectronicsOrHardwareManufacturing".freeze
    AUTOMOTIVE_MANUFACTURING = "AutomotiveManufacturing".freeze
    CONSTRUCTION_MATERIALS = "ConstructionMaterials".freeze
    TEXTILES_OR_APPAREL = "TextilesOrApparel".freeze
    MINING = "Mining".freeze
    REAL_ESTATE = "RealEstate".freeze
    CONSTRUCTION = "Construction".freeze
    TRANSPORTATION_OR_WAREHOUSING = "TransportationOrWarehousing".freeze
    WHOLESALE_TRADE = "WholesaleTrade".freeze
    BUSINESS_SUPPORT_OR_BUILDING_SERVICES = "BusinessSupportOrBuildingServices".freeze
    ESCORT_SERVICES = "EscortServices".freeze
    DATING_OR_ADULT_ENTERTAINMENT = "DatingOrAdultEntertainment".freeze

    def self.all_vars
      @all_vars ||= [GROCERY_STORES_OR_SUPERMARKETS, CONVENIENCE_STORES, SPECIALTY_FOOD_RETAILERS, GAS_STATIONS_WITH_RETAIL, GENERAL_MERCHANDISE_OR_DEPARTMENT_STORES, ONLINE_RETAIL_OR_E_COMMERCE, SUBSCRIPTION_AND_MEMBERSHIP_PLATFORMS, DIRECT_TO_CONSUMER_BRANDS, CANNABIS, BANKS_OR_CREDIT_UNIONS, FIN_TECH_OR_PAYMENT_PROCESSING, INSURANCE_PROVIDERS, INVESTMENT_ADVISORS_OR_BROKER_DEALERS, LENDING_OR_MORTGAGE_COMPANIES, TREASURY_MANAGEMENT_PLATFORMS, PERSONAL_FINANCE_APPS_OR_AI_ASSISTANTS, RETIREMENT_PLANNING, REAL_ESTATE_INVESTMENT_PLATFORMS, MONEY_SERVICE_BUSINESSES, CRYPTOCURRENCY, DEBT_COLLECTION, PAYDAY_LENDING, GAMBLING, FARMS_OR_AGRICULTURAL_PRODUCERS, FOOD_WHOLESALERS_OR_DISTRIBUTORS, RESTAURANTS_OR_CAFES, BARS_OR_NIGHTCLUBS, CATERING_SERVICES, FARMERS_MARKETS, RESTAURANT_TECH_AND_POS_PROVIDERS, HOSPITALS_OR_CLINICS, PHARMACIES, MEDICAL_EQUIPMENT_SUPPLIERS, BIOTECHNOLOGY_FIRMS, HOME_HEALTH_SERVICES, HEALTHCARE_STAFFING_PLATFORMS, WELLNESS_AND_BENEFITS_PLATFORMS, HEALTHCARE_AND_SOCIAL_ASSISTANCE, LEGAL_SERVICES, ACCOUNTING_OR_AUDITING_FIRMS, CONSULTING_FIRMS, MARKETING_OR_ADVERTISING_AGENCIES, REAL_ESTATE_AGENTS_OR_PROPERTY_MANAGERS, CORPORATE_SERVICES_AND_INCORPORATION, HR_AND_WORKFORCE_MANAGEMENT_PLATFORMS, DIRECT_MARKETING_OR_TELEMARKETING, LEGAL_ACCOUNTING_CONSULTING_OR_COMPUTER_PROGRAMMING, CHEMICAL_MANUFACTURING, ELECTRONICS_OR_HARDWARE_MANUFACTURING, AUTOMOTIVE_MANUFACTURING, CONSTRUCTION_MATERIALS, TEXTILES_OR_APPAREL, MINING, REAL_ESTATE, CONSTRUCTION, TRANSPORTATION_OR_WAREHOUSING, WHOLESALE_TRADE, BUSINESS_SUPPORT_OR_BUILDING_SERVICES, ESCORT_SERVICES, DATING_OR_ADULT_ENTERTAINMENT].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ThreadBusinessIndustry.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ThreadBusinessIndustry"
    end
  end
end
