=begin
#Unit OpenAPI specifications

#An OpenAPI specifications for unit-sdk clients

The version of the OpenAPI document: 0.0.2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'cgi'

module OpenapiClient
  class CreateCounterpartyApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create Counterparty
    # Create a counterparty via API 
    # @param create_counterparty [CreateCounterparty] Create Counterparty Request
    # @param [Hash] opts the optional parameters
    # @return [UnitCounterpartyResponse]
    def execute(create_counterparty, opts = {})
      data, _status_code, _headers = execute_with_http_info(create_counterparty, opts)
      data
    end

    # Create Counterparty
    # Create a counterparty via API 
    # @param create_counterparty [CreateCounterparty] Create Counterparty Request
    # @param [Hash] opts the optional parameters
    # @return [Array<(UnitCounterpartyResponse, Integer, Hash)>] UnitCounterpartyResponse data, response status code and response headers
    def execute_with_http_info(create_counterparty, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CreateCounterpartyApi.execute ...'
      end
      # verify the required parameter 'create_counterparty' is set
      if @api_client.config.client_side_validation && create_counterparty.nil?
        fail ArgumentError, "Missing the required parameter 'create_counterparty' when calling CreateCounterpartyApi.execute"
      end
      # resource path
      local_var_path = '/counterparties'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/vnd.api+json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/vnd.api+json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(create_counterparty)

      # return_type
      return_type = opts[:debug_return_type] || 'UnitCounterpartyResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"CreateCounterpartyApi.execute",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CreateCounterpartyApi#execute\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
