name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-openapi-ruby-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Execute tests
        run: bundle exec rspec
        env:
          UNIT_TOKEN: ${{ secrets.UNIT_TOKEN }}
          TEST_PLAID_TOKEN: ${{ secrets.TEST_PLAID_TOKEN }}

      - name: Execute Rake build
        run: bundle exec rake build
