name: Publish gem to RubyOrgs
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "3.2.0"

      - name: Install dependencies
        uses: bundle install

      - name: Execute Rake build
        run: bundle exec rake build

      - name: Publish to RubyGems
        run: |
          touch $HOME/pkg/credentials
          chmod 0600 $HOME/pkg/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/pkg/credentials
          gem push ./pkg/*.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
